name: Example workflow for App Center action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Upload aab file to production track of the Play Store
        uses: ./
        with:
          command: appcenter distribute stores publish -s Alpha -f app/build/outputs/apk/release/app-release-unsigned.apk -r "Release note" -a user/app
          token: Test Token
